# -*- coding: utf-8 -*-
"""fibonacci number

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g0cR1qJmPkuaIim-_TqNFvsL8RbQ5JB4
"""

def generate_fib(limit):
  fib_sequence = [0, 1]
  while fib_sequence[-1] + fib_sequence[-2] <= limit:
    next_number = fib_sequence[-1] + fib_sequence[-2]
    fib_sequence.append(next_number)

  return fib_sequence

limit = 144
fibonacci_number = generate_fib(limit=144)
print("Fib numbers upto 144")
print(fibonacci_number)

print(fibonacci_number)