# -*- coding: utf-8 -*-
"""inputlist.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10RFxOszuIboW6QhnyfrOUiTLnyBZ-h-6
"""



list1 = [12, -7, 5, 64, -14]
list2 = [12, 14, -95, 3]
print(list1)
print(list2)